volumes:
  home_data:

services:
  workspace:
    image: ${DOCKER_IMAGE_REPOSITORY}:${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    build:
      context: ./
      args:
        # Timezone
        TZ: ${TZ}
        # User configuration
        USERNAME: ${USERNAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        # Python & Ansible
        INSTALL_PYTHON: ${INSTALL_PYTHON}
        INSTALL_ANSIBLE: ${INSTALL_ANSIBLE}
        # Node.js tools
        INSTALL_VOLTA: ${INSTALL_VOLTA}
        # CLI tools
        TASK_VERSION: ${TASK_VERSION}
        LAZYDOCKER_VERSION: ${LAZYDOCKER_VERSION}
        YQ_VERSION: ${YQ_VERSION}
        LAZYGIT_VERSION: ${LAZYGIT_VERSION}
        # Kubernetes tools
        INSTALL_K8S: ${INSTALL_K8S}
        KUBECTL_VERSION: ${KUBECTL_VERSION}
        HELM_VERSION: ${HELM_VERSION}
        K9S_VERSION: ${K9S_VERSION}
    restart: unless-stopped
    working_dir: ${APP_CODE_PATH_CONTAINER}
    tty: true
    # volumes:
    #   - home_data:/home/${USERNAME}
