networks:
  ws-net:
    driver: bridge

volumes:
  home_data:
  docker_data:

services:
  workspace:
    image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BASE_IMAGE_NAME: ${BASE_IMAGE_NAME}
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
        IMAGE_TAG: ${IMAGE_TAG}
        TZ: ${TZ}
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        ROOT_PASSWORD: ${ROOT_PASSWORD}
        USER_PASSWORD: ${USER_PASSWORD}
        # Development Tools Installation Flags
        INSTALL_SUPERVISOR: ${INSTALL_SUPERVISOR}
        INSTALL_ANSIBLE: ${INSTALL_ANSIBLE}
        INSTALL_K6: ${INSTALL_K6}
        INSTALL_ZELLIJ: ${INSTALL_ZELLIJ}
        INSTALL_GUM: ${INSTALL_GUM}
        INSTALL_GETOPTIONS: ${INSTALL_GETOPTIONS}
        INSTALL_AWS_CLI: ${INSTALL_AWS_CLI}
        INSTALL_DRY: ${INSTALL_DRY}
        INSTALL_LAZYDOCKER: ${INSTALL_LAZYDOCKER}
        INSTALL_GITHUB_CLI: ${INSTALL_GITHUB_CLI}
        INSTALL_CLOUDFLARED: ${INSTALL_CLOUDFLARED}
        INSTALL_LAZYGIT: ${INSTALL_LAZYGIT}
        INSTALL_NGROK: ${INSTALL_NGROK}
        INSTALL_STARSHIP: ${INSTALL_STARSHIP}
        INSTALL_TAILSCALE: ${INSTALL_TAILSCALE}
        INSTALL_TASK: ${INSTALL_TASK}
        INSTALL_TERRAFORM: ${INSTALL_TERRAFORM}
        INSTALL_TELEPORT: ${INSTALL_TELEPORT}
        INSTALL_KUBECTL: ${INSTALL_KUBECTL}
        INSTALL_HELM: ${INSTALL_HELM}
        INSTALL_K9S: ${INSTALL_K9S}
        INSTALL_GOMPLATE: ${INSTALL_GOMPLATE}
        INSTALL_DBEAVER: ${INSTALL_DBEAVER}
        INSTALL_MISE: ${INSTALL_MISE}
        INSTALL_UV: ${INSTALL_UV}
        INSTALL_VOLTA: ${INSTALL_VOLTA}
        INSTALL_WP_CLI: ${INSTALL_WP_CLI}
    # restart: unless-stopped
    working_dir: ${HOME_DIR}
    # tty: true
    # ports:
    #   - "${SSH_FORWARD_PORT}:${SSH_PORT}"
    networks:
      - ws-net
    ports:
      - "9001:9001"
    # volumes:
    #   # - home_data:/home/${USER_NAME}
    #   - ./resources/prebuildfs/opt/laragis/common/tools/04-modern-pkgs.sh:/opt/laragis/common/tools/04-modern-pkgs.sh


