#!/bin/sh
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
set -eu

set -eu

n=0
max=2

until [ "$n" -gt "$max" ]; do
  set +e

  (
    dnf -y \
      --setopt=clean_requirements_on_remove=1 \
      remove "$@"
  )
  CODE=$?
  set -e

  if [ "$CODE" -eq 0 ]; then
    break
  fi

  if [ "$n" -eq "$max" ]; then
    exit "$CODE"
  fi

  echo "dnf failed, retrying" >&2
  n=$((n + 1))
done

dnf -y clean all
rm -rf /var/cache/dnf /var/cache/yum